--create Table _chain_blocks
CREATE TABLE _chain_blocks(
	ID VARCHAR(11) NOT NULL,
	CHANNEL_NAME VARCHAR(32),
	BLOCK_NUM VARCHAR(11),
	CURRENT_HASH VARCHAR(256),
	PRE_HASH VARCHAR(256),
	TX_COUNT VARCHAR(11),
	TIME VARCHAR
);
ALTER TABLE _chain_blocks ADD CONSTRAINT _chain_blocks_PK PRIMARY KEY (ID);
